### ISSUE TITLE
Support for netcoreapp2.0

### ISSUE THREAD

**Issue by dazinator** [stazz/UtilPack#3] opened 2017-09-13 10:59 UTC
I found your msbuild task factory via: https://github.com/Microsoft/msbuild/issues/1756 as I was struggling to have my msbuild task loaded from a nuget package when building under netcoreapp2.0.

I notice netcoreapp2.0 isn't explicitly handled anywhere yet - does support for netcoreapp2.0 need to be added?

**Comment by stazz** [comment] 2017-09-13 12:07
There isn't auto-detection of the SDK package for .NET Core App 2.0 (Microsoft.NETCore.App, 2.0.0). However, currently, this shouldn't cause much trouble (other than slowdown, since it queries nuget.org server every time you use the task), since the task factory ends up restoring the newest version of Microsoft.NETCore.App package, which just happens to be 2.0.0. :)

If you are getting assembly-loading-related errors when running your task, and you suspect this issue might be the cause, you can specify the SDK package version by using `NuGetFrameworkPackageVersion` task factory parameter, like this:

```xml
<UsingTask
  Condition=" '$(UtilPackNuGetMSBuildAssemblyPath)' != '' "
  TaskFactory="UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory"
  AssemblyFile="$(UtilPackNuGetMSBuildAssemblyPath)"
  TaskName="YourTaskNameHere"
>
  <Task>
    <NuGetTaskInfo>
      <PackageID>YourTaskPackageID</PackageID>
      <PackageVersion>YourTaskPackageVersion</PackageVersion>
      <NuGetFrameworkPackageVersion>2.0.0</NuGetFrameworkPackageVersion>
    </NuGetTaskInfo>
  </Task>
</UsingTask>
```

Let me know if you are getting any assembly-resolve errors when running your task. In any case, I will add auto-detection of the SDK package for .NET Core App 2.0 later today, or tomorrow.

P.S. I assume you are trying to run your task via MSBuild 15.3. for .NET Core (`dotnet msbuild` command). If your task targets .NET Core 2.0, it most likely will fail to run on .NET Desktop (`c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` command) .

**Comment by dazinator** [comment] 2017-09-13 12:22
Thanks.

I am multi-targeting my task for netcoreapp20 and net461 currently, so there are two seperate assemblies within my nuget package.  I condition an msbuild property to point to the correct assembly path based on the environment the build is running under. So this hopefully means when running under netcore the `AssemblyFile` param to your task factory should be pointing to the netcoreapp2.0 compiled assembly, and when running under desktop it should point to the net461 assembly. However longer term I beelive your task factory should allow me (if I understand correctly) to compile a single task for netstandard so that I can eliminate this logic?

**Comment by dazinator** [comment] 2017-09-13 12:28
>  I assume you are trying to run your task via MSBuild 15.3. for .NET Core 

I am currently using the 15.5 preview msbuild packages for netcoreapp2.0 because these allowed me to run msbuild directly within an NUnit tests project so that I can test building a project file that has a package reference to my tasks nuget package, and then verify my expectations around project outputs. However, it looks like depending on 15.5 versions of the packages causes an issue when building via the `dotnet cli` (dotnet build) as dotnet cli raises invalid cast exceptions saying it cant cast between identical types (ITask[] and ITask[]) - so assume it must be a version mismatch thing going on.

So I think I am currently in this situation: In order to run my netcoreapp2.0 tests - I need to use 15.5 preview packages of msbuild, but in order for my msbuild task to run under `dotnet cli` I think I need to depend on the 15.3 version of the packages. When multitargeting, I can't distinguish between both cases - I can only target netcoreapp2.0!

My head hurts more and more each day.

**Comment by stazz** [comment] 2017-09-13 12:36
Ah - you don't need to specifically use `AssemblyPath` task factory parameter, unless your package contains multiple assemblies in one target framework folder. The task factory itself will know in which environment it is running, and load the correct version of your task assembly automatically (`lib|build/net461/YourTaskAssembly.dll`, or `lib|build/netcoreapp20/YourTaskAssembly.dll`). If it doesn't, there is a bug in the task factory related to that logic and should be fixed. If you have more questions about this, could you please provide small example of your .csproj file where you use the task factory so I can get a better idea what's going on? :)

And yes, once there is .NET Desktop version which is .NET Standard 2.0 -compliant, you can just compile against .NET Standard 2.0, and your task should be runnable by both .NET Desktop and .NET Core environments using UtilPack.NuGet.MSBuild task factory - without any hassle of detecting the environment.

Testing MSBuild tasks is a huge PITA. Are the casting errors coming from MSBuild itself or the UtilPack.NuGet.MSBuild task factory? The task factory should be prepared for version mismatches related to MSBuild assemblies, since the desktop version of the task factory is compiled against MSBuild 14.3.

**Comment by dazinator** [comment] 2017-09-13 12:37
> The task factory itself will know in which environment it is running, and load the correct version of your task assembly automatically 

Ok brilliant. I'll make sure the assemblies go in the correct folders and then all should be good then.

**Comment by dazinator** [comment] 2017-09-13 12:39
> Are the casting errors coming from MSBuild itself or the UtilPack.NuGet.MSBuild task factory? 

Oh yeah msbuild / dotnet cli - nothing to do with `UtilPack.NuGet.MSBuild`.

I'll let you know how I get on.

**Comment by stazz** [comment] 2017-09-15 10:23
Closing this one, as UtilPack.NuGet.MSBuild package now (since version 1.1.2) is .NET Core App 2.0 -aware, and won't cause slowdown, and I guess silence means that no more errors have arised. :) If you have any more trouble with any of the project in this repository, feel free to open a new issue! 👍

**Closed as completed by stazz** 2017-09-15 10:23 UTC
Labels: enhancement
